In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3])

print(v)

[1 2 3]


In [3]:
v = np.array([[1],[2],[3]])

print(v)

[[1]
 [2]
 [3]]


In [4]:
matrix = np.array([[1,2,3],[2,4,6],[4,2,1]])
print(matrix)

[[1 2 3]
 [2 4 6]
 [4 2 1]]


In [5]:
v = np.array([1,2,3,4,5,6,7])
print(v[3])

4


In [6]:
v

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
v[:]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
v[2:5]

array([3, 4, 5])

In [9]:
v[2:2]

array([], dtype=int32)

In [10]:
v[-1]

7

In [11]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
m[0,0]

1

In [14]:
m[1,1]

5

In [15]:
m[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [16]:
m[:3,:1]

array([[1],
       [4],
       [7]])

In [17]:
m[:3,:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [18]:
m[:3,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
m[:,1:2]

array([[2],
       [5],
       [8]])

In [21]:
m[1:2,1:2]

array([[5]])

In [22]:
m[1:2,:]

array([[4, 5, 6]])

In [ ]:
00  01  02
10  11  12
20  21  22

In [24]:
matrix = np.array([[1,2,3,4], [4,5,6,4], [7,8,9,13]])

print(matrix)

[[ 1  2  3  4]
 [ 4  5  6  4]
 [ 7  8  9 13]]


In [25]:
print(matrix.shape)

(3, 4)


In [26]:
print(matrix.size)

12


In [27]:
print(matrix.ndim)

2


In [28]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(np.max(matrix))

9


In [30]:
print(np.min(matrix))

1


In [31]:
print(np.max(matrix, axis=0)) 

[7 8 9]


In [32]:
print(np.max(matrix, axis=1)) # row

[3 6 9]


In [33]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(np.mean(matrix))  # 45/9 = 5.0

5.0


In [36]:
print(np.var(matrix))

6.666666666666667


In [37]:
print(np.std(matrix))

2.581988897471611


In [38]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(matrix.shape)

(3, 3)


In [40]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [41]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [42]:
print(matrix.reshape(9))  # 1 - d array

[1 2 3 4 5 6 7 8 9]


In [43]:
print(matrix.reshape(1,-1))

[[1 2 3 4 5 6 7 8 9]]


In [44]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


In [45]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [47]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
print(np.linalg.det(matrix))

6.66133814775094e-16


In [49]:
print(np.linalg.matrix_rank(matrix))  # number of non zero rows

2


In [51]:
np.random.seed(5)

print(np.random.randint(0,11,3))

[3 6 6]


In [52]:
print(np.random.normal(1.0, 2.0, 10))  # normal distribution

[ 0.95339251  2.68355533  3.73517105  2.14941538 -2.77152482  1.34185074
  0.19381338  4.27525698 -0.2105957  -2.18883015]
